version: "3.7"
services:
  app:
    build:
      args:
        user: docker
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on: 
      - nginx
      - db
      - redis

  db:
    image: mariadb:lts
    ports:
      - "3307:3306"
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8088:80
      - 5173:5173
    volumes:
      - ./:/var/www
      - ./.docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6389:6379"
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  db_data: {}